### ISSUE TITLE
youtube-chat won't start up/work

### ISSUE THREAD

**Issue by Delta-official** [LinaTsukusu/youtube-chat#12]
I am trying to get the Youtube chat messages but `youtube-chat` wouldn't even emit the "start" event, i've had a hidden stream running while running my code.
Here's my code:
```javascript
function initInterpreter() {

const LC = new LiveChat({channelId: "UCaT3tgLp3NYg_UwcU_D2nvQ"}); // Stratzenblitz channel ID: UCTIgONilLxeAPqkiZrqZOzg

LC.on("start", (LiveId) => {
    YT_Display.YT_Connect();
    console.log(chalk.yellow(`Youtube live chat ID: ${LiveId}`));
});

LC.on("end", (reason) => {
    YT_Display.YT_Disconnect();
    console.log(chalk.yellow(`Reason: ${reason}`));
});

LC.on("comment", async (comment) => {
    var command = await checkCommands();
    switch(command) {
        case "left":
            console.log("Left");
            break;
        case "right": 
            console.log("right");
            break;
        case "back":
            console.log("backwards");
            break;
        case "forward":
            console.log("forwards");
            break;
    }
});

LC.on("error", (err) => {
    YT_Display.YT_Error();
    console.log(chalk.hex("#db0000")(err));
});

}

initInterpreter();
```

**Comment by Chipsnet** [comment]
you must do `LC.start();`

**Comment by neverclear86** [comment]
@Delta-official 
Sorry for the confusing readme.
Do `LC.start()` to start getting chats

**Comment by Delta-official** [comment]
Hm, thank you for help. But now another problem has appeared: the code displays an error that says `Cannot find module tslib`. I've tried running `npm install` in the `youtube-chat` directory, but it did nothing.

I will open another issue about this problem.

**Comment by Delta-official** [comment]
Hm, thank you for help. But now another problem has appeared: the code displays an error that says `Cannot find module tslib`. I've tried running `npm install` in the `youtube-chat` directory, but it did nothing.

I will open another issue about this problem.

**Comment by Chipsnet** [comment]
I had the exact same problem, but I solved it by running `yarn add tslib`.
If you are using npm, replace it and run it.
