### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by sasagar** [LinaTsukusu/youtube-chat#14]
I got the error when start fetching the chat.
It says...

```
(node:2864) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'contents' of undefined
    at LiveChat.fetchChat (webpack:///./node_modules/youtube-chat/dist/live-chat.js?:50:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
```

I don't know what part is the content means.
Any suggestions?

**Comment by neverclear86** [comment]
Youtube may have changed their specs again recently, so if it's not fixed, please wait for the my fix!

**Comment by sasagar** [comment]
This change of YouTube should not be bug or something like that.
We should fix it for the new specs.

(I hope I can help it but I don't have enough skill for that...)

**Comment by KarasuTatehi** [comment]
> **Note:** This message has been translated by DeepL.

On January 29, the URL used to retrieve JSON seems to have been changed to `https://www.youtube.com/youtubei/v1/live_chat/get_live_chat?key={innertubeApiKey}`.

You need to find the `innertubeApiKey` in the source code of the delivery page you are playing.
It does not appear to be possible to retrieve the JSON in one step currently.

> **Source (Japanese) :**
> https://qiita.com/pasta04/items/ec7ed6ded14d5af1663e

**Comment by Chipsnet** [comment]
When I using this fork https://github.com/IcedCoffeee/youtube-chat/commit/3e20049 , I got the following errors.

```
(node:10376) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'text' of undefined
    at LiveChat.<anonymous> (C:\Users\Minato86\Desktop\youtube live get test\main.js:58:46)
    at LiveChat.emit (events.js:315:20)
    at C:\Users\Minato86\Desktop\youtube live get test\node_modules\youtube-chat\dist\live-chat.js:87:18
    at Array.forEach (<anonymous>)
    at LiveChat.fetchChat (C:\Users\Minato86\Desktop\youtube live get test\node_modules\youtube-chat\dist\live-chat.js:86:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by TentacleSama4254** [comment]
Still the same error

**Comment by TentacleSama4254** [comment]
> 
> 
> Youtube may have changed their specs again recently, so if it's not fixed, please wait for the my fix!

jjust a reminde to get this working if you can

**Comment by Chipsnet** [comment]
I was not able to get it to work this way.
So, I had to get the API Key and build a program to run the official API.

**Comment by TentacleSama4254** [comment]
> I was not able to get it to work this way.
> So, I had to get the API Key and build a program to run the official API.

Did you make a repo for that too?

**Comment by neverclear86** [comment]
It will be closed as it will be supported by version 2.
