### ISSUE TITLE
README通りにメソッドを呼ぶと型エラーになる

### ISSUE THREAD

**Issue by pasta04** [LinaTsukusu/youtube-chat#4]
## 対象ファイル
- README.md

## 事象
`Getting started`の`4.Add events`において、
以下のように呼んでいますが、
```
liveChat.on('end', (reason: string) => {})
```
TypeScript 3.8.3 strict設定の時、上記では型エラーになりました。

## 対策
型定義に従った場合、以下ではないでしょうか。
```
liveChat.on('end', (reason?: string) => {})
```

**Comment by neverclear86** [comment]
実際には型定義があるので引数の型指定はいらないため､READMEの表記を変更しました｡
また､v1.1.0でビルドエラーになる問題とチャンネルIDから配信IDが取得できなくなっていた不具合を修正しました｡💪
