### ISSUE TITLE
Error: Refused to set unsafe header "user-agent"

### ISSUE THREAD

**Issue by PrestonN** [LinaTsukusu/youtube-chat#6]
Hello!  This project is really nice and it works well.  I'm very pleased with the functionality of this project.

I do have a problem, however it's more of an annoyance than anything.  While connected to a chat, there's a constant error that gets spammed into the console.

```
Refused to set unsafe header "user-agent"
```

Simply removing the user agent string [here](https://github.com/LinaTsukusu/youtube-chat/blob/master/src/live-chat.ts#L11) seems to get rid of this error.  I can make a PR for this though I'm not sure if there are other reasons for setting this user-agent.

**Comment by neverclear86** [comment]
It will be closed as it will be supported by version 2.
