### ISSUE TITLE
Moderators are treated like owners

### ISSUE THREAD

**Issue by Zestrial** [LinaTsukusu/youtube-chat#8]
If a moderator sends a message to the chat, `isOwner` will be true

**Comment by Draguwro** [comment]
Here's a GIF of what's happening when I output the chat comment: 

![uhCHlis](https://user-images.githubusercontent.com/37517470/103135437-53c65180-4686-11eb-8e70-cc846eb64cb6.gif)

Even though this channel isn't the broadcaster, it's still treated like an owner because `author.isOwner` is true.

**Comment by nvlled** [comment]
Not sure if you already fixed it but I submitted a fix on this pull request https://github.com/LinaTsukusu/youtube-chat/pull/10

**Comment by Draguwro** [comment]
@nvlled I did fix this specific problem, but your PR accounts for verified people too 👍

**Comment by neverclear86** [comment]
Close it now that it has merged.
